#!/opt/local/bin/python
import sys, os

# list of python scripts in sequence to execute

installPath = ""
target = ""
optimization = ""
companyName = ""
productName = ""
width = ""
height = ""

scriptDir = os.path.dirname(sys.argv[0])
mac_pyscripts = ('googleplay_xcode.py',)
logfilePath = os.path.join(scriptDir,"nerbuild.log")
logfile = open(logfilePath,'w+')
def log_error(msg):
	logfile.write("ERROR:%s\n" % (msg))

def log_debug(msg):
	logfile.write("DEBUG:%s\n" % (msg))


log_debug("Params %s" % (sys.argv))
try:
	installPath = sys.argv[1]
	target = sys.argv[2]
	optimization = sys.argv[3]
	companyName = sys.argv[4]
	productName = sys.argv[5]
	width = sys.argv[6]
	height = sys.argv[7]
except:
	log_error("Not all 7 parameters were received")

for scr in mac_pyscripts:
	log_debug("Executing %s" % (scr))
	if os.system("%s %s %s %s %s %s %s %s >> %s 2>&1" % (os.path.join(scriptDir, scr), installPath, target, optimization, companyName, productName, width, height, logfilePath)) != 0: 
		# we had error and that means we should not do other scripts
		log_error("Error in executing script %s\nAborting" % (scr))
		break
	log_debug("Finished script %s" %(scr))	



logfile.close()
